## CNN - Convulution Neural Network

In [5]:
import tensorflow as tf

import numpy as np
from tensorflow import keras
from sklearn.model_selection import train_test_split
import pandas as pd

In [14]:
df = pd.DataFrame({
    "soil_moisture" : [0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.50, 0.60, 0.18, 0.45, 0.80],
    "temperature_c" : [34, 30, 26, 22, 28, 30, 19, 22, 25, 33, 12, 21],
    "sunlight_hours" : [9, 8, 7, 4, 8, 10, 12, 5, 9, 11, 3, 9],
    "needs_water" : [1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0],
})
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            1
4            0.30             28               8            0
5            0.35             30              10            0
6            0.40             19              12            0
7            0.50             22               5            0
8            0.60             25               9            1
9            0.18             33              11            0
10           0.45             12               3            1
11           0.80             21               9            0

In [15]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [16]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [17]:
X_min = X.min()
X_max = X.max()

In [18]:
# mean median mode

X_scaled = (X-X_min) / (X_max-X_min + 1e-8)
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.000000       1.000000        0.666667
1        0.071429       0.818182        0.555556
2        0.142857       0.636364        0.444444
3        0.214286       0.454545        0.111111
4        0.285714       0.727273        0.555556
5        0.357143       0.818182        0.777778
6        0.428571       0.318182        1.000000
7        0.571429       0.454545        0.222222
8        0.714286       0.590909        0.666667
9        0.114286       0.954545        0.888889
10       0.500000       0.000000        0.000000
11       1.000000       0.409091        0.666667

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.20, random_state=42,stratify=y)

In [46]:
from tensorflow.keras import layers
model = keras.Sequential(
    [
        layers.Input(shape = (X_train.shape[1], )),
        layers.Dense(8,activation='relu'),
        layers.Dense(1,activation='sigmoid')

    ]

)

In [47]:
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

In [48]:

history_full = model.fit(X_train.values, y_train.values.reshape(-1,1), epochs=100, batch_size=50, verbose=1)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.4444 - loss: 0.7923
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.4444 - loss: 0.7893
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.4444 - loss: 0.7863
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.4444 - loss: 0.7834
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.4444 - loss: 0.7805
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4444 - loss: 0.7776
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4444 - loss: 0.7748
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4444 - loss: 0.7719
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.4444 - loss: 0.7691
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4444 - loss: 0.7664
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.4444 - loss: 0.7636
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4444 - loss: 0.7609
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.4444 - loss: 0.7582
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.4444 - loss: 0.7555
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4444 - loss: 0.7528
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.4444 - loss: 0.7502
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.4444 - loss: 0.7476
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.4444 - loss: 0.7450
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4444 - loss: 0.7424
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4444 - loss: 0.7399
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4444 - loss: 0.7374
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4444 - loss: 0.7350
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4444 - loss: 0.7325
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4444 - loss: 0.7301
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.4444 - loss: 0.7277
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.4444 - loss: 0.7253
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.4444 - loss: 0.7230
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.4444 - loss: 0.7207
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.4444 - loss: 0.7184
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4444 - loss: 0.7162
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4444 - loss: 0.7139
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4444 - loss: 0.7117
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5556 - loss: 0.7096
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5556 - loss: 0.7074
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5556 - loss: 0.7052
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5556 - loss: 0.7030
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5556 - loss: 0.7009
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.5556 - loss: 0.6988
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5556 - loss: 0.6967
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.5556 - loss: 0.6947
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5556 - loss: 0.6926
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5556 - loss: 0.6906
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5556 - loss: 0.6886
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5556 - loss: 0.6866
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5556 - loss: 0.6847
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5556 - loss: 0.6828
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5556 - loss: 0.6810
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5556 - loss: 0.6792
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5556 - loss: 0.6773
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5556 - loss: 0.6755
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5556 - loss: 0.6737
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5556 - loss: 0.6719
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5556 - loss: 0.6702
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5556 - loss: 0.6684
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5556 - loss: 0.6668
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5556 - loss: 0.6651
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5556 - loss: 0.6634
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5556 - loss: 0.6618
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5556 - loss: 0.6602
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5556 - loss: 0.6586
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5556 - loss: 0.6570
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.5556 - loss: 0.6554
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5556 - loss: 0.6539
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5556 - loss: 0.6523
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5556 - loss: 0.6508
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5556 - loss: 0.6493
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5556 - loss: 0.6479
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5556 - loss: 0.6465
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5556 - loss: 0.6450
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5556 - loss: 0.6437
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5556 - loss: 0.6423
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5556 - loss: 0.6409
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5556 - loss: 0.6396
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5556 - loss: 0.6382
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5556 - loss: 0.6369
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5556 - loss: 0.6356
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5556 - loss: 0.6344
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5556 - loss: 0.6331
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6667 - loss: 0.6318
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6667 - loss: 0.6306
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6667 - loss: 0.6294
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.6283
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6667 - loss: 0.6271
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6667 - loss: 0.6259
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6667 - loss: 0.6248
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6667 - loss: 0.6236
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6667 - loss: 0.6225
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6667 - loss: 0.6214
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6667 - loss: 0.6203
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6667 - loss: 0.6192
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6667 - loss: 0.6182
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6667 - loss: 0.6171
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6667 - loss: 0.6160
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6667 - loss: 0.6150
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6667 - loss: 0.6139
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6667 - loss: 0.6129
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6667 - loss: 0.6119
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6667 - loss: 0.6109
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6667 - loss: 0.6099
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6667 - loss: 0.6089

In [49]:
history = model.fit(
    X_train.values,y_train.values.reshape(-1,1),
    validation_data = (X_test.values, y_test.values.reshape(-1,1)),
    epochs = 100,
    batch_size = 1,
    verbose=1
)

Epoch 1/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.6052 - val_accuracy: 0.6667 - val_loss: 0.7145
Epoch 2/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6667 - loss: 0.6000 - val_accuracy: 0.6667 - val_loss: 0.7192
Epoch 3/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6667 - loss: 0.5941 - val_accuracy: 0.6667 - val_loss: 0.7224
Epoch 4/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6667 - loss: 0.5902 - val_accuracy: 0.6667 - val_loss: 0.7243
Epoch 5/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6667 - loss: 0.5862 - val_accuracy: 0.6667 - val_loss: 0.7287
Epoch 6/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6667 - loss: 0.5828 - val_accuracy: 0.6667 - val_loss: 0.7326
Epoch 7/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7778 - loss: 0.5795 - val_accuracy: 0.6667 - val_loss: 0.7342
Epoch 8/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7778 - loss: 0.5761 - val_accuracy: 0.6667 - val_loss: 0.7372
Epoch 9/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.5754 - val_accuracy: 0.6667 - val_loss: 0.7408
Epoch 10/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.5709 - val_accuracy: 0.6667 - val_loss: 0.7435
Epoch 11/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5677 - val_accuracy: 0.6667 - val_loss: 0.7453
Epoch 12/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5658 - val_accuracy: 0.6667 - val_loss: 0.7478
Epoch 13/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5640 - val_accuracy: 0.3333 - val_loss: 0.7505
Epoch 14/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5614 - val_accuracy: 0.3333 - val_loss: 0.7520
Epoch 15/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5590 - val_accuracy: 0.3333 - val_loss: 0.7554
Epoch 16/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5564 - val_accuracy: 0.3333 - val_loss: 0.7566
Epoch 17/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.5547 - val_accuracy: 0.3333 - val_loss: 0.7588
Epoch 18/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5532 - val_accuracy: 0.3333 - val_loss: 0.7615
Epoch 19/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5515 - val_accuracy: 0.3333 - val_loss: 0.7614
Epoch 20/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5495 - val_accuracy: 0.3333 - val_loss: 0.7660
Epoch 21/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5464 - val_accuracy: 0.3333 - val_loss: 0.7675
Epoch 22/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.5439 - val_accuracy: 0.3333 - val_loss: 0.7681
Epoch 23/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5425 - val_accuracy: 0.3333 - val_loss: 0.7697
Epoch 24/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5416 - val_accuracy: 0.3333 - val_loss: 0.7728
Epoch 25/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.5383 - val_accuracy: 0.3333 - val_loss: 0.7741
Epoch 26/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.5367 - val_accuracy: 0.3333 - val_loss: 0.7739
Epoch 27/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.5356 - val_accuracy: 0.3333 - val_loss: 0.7772
Epoch 28/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.5322 - val_accuracy: 0.3333 - val_loss: 0.7773
Epoch 29/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5305 - val_accuracy: 0.3333 - val_loss: 0.7778
Epoch 30/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.5284 - val_accuracy: 0.3333 - val_loss: 0.7807
Epoch 31/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.5270 - val_accuracy: 0.3333 - val_loss: 0.7837
Epoch 32/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.5246 - val_accuracy: 0.3333 - val_loss: 0.7836
Epoch 33/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.5230 - val_accuracy: 0.3333 - val_loss: 0.7865
Epoch 34/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - loss: 0.5208 - val_accuracy: 0.3333 - val_loss: 0.7871
Epoch 35/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.5190 - val_accuracy: 0.3333 - val_loss: 0.7894
Epoch 36/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - loss: 0.5172 - val_accuracy: 0.3333 - val_loss: 0.7913
Epoch 37/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.5158 - val_accuracy: 0.3333 - val_loss: 0.7939
Epoch 38/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - loss: 0.5136 - val_accuracy: 0.3333 - val_loss: 0.7940
Epoch 39/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.5124 - val_accuracy: 0.3333 - val_loss: 0.7937
Epoch 40/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.5097 - val_accuracy: 0.3333 - val_loss: 0.7966
Epoch 41/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - loss: 0.5079 - val_accuracy: 0.3333 - val_loss: 0.7988
Epoch 42/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.5069 - val_accuracy: 0.3333 - val_loss: 0.8013
Epoch 43/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8889 - loss: 0.5041 - val_accuracy: 0.3333 - val_loss: 0.8023
Epoch 44/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.5035 - val_accuracy: 0.3333 - val_loss: 0.8035
Epoch 45/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.5010 - val_accuracy: 0.3333 - val_loss: 0.8054
Epoch 46/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.5014 - val_accuracy: 0.3333 - val_loss: 0.8055
Epoch 47/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8889 - loss: 0.4997 - val_accuracy: 0.3333 - val_loss: 0.8098
Epoch 48/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8889 - loss: 0.4952 - val_accuracy: 0.3333 - val_loss: 0.8117
Epoch 49/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8889 - loss: 0.4932 - val_accuracy: 0.3333 - val_loss: 0.8139
Epoch 50/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8889 - loss: 0.4911 - val_accuracy: 0.3333 - val_loss: 0.8161
Epoch 51/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.4891 - val_accuracy: 0.3333 - val_loss: 0.8188
Epoch 52/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8889 - loss: 0.4873 - val_accuracy: 0.3333 - val_loss: 0.8221
Epoch 53/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8889 - loss: 0.4851 - val_accuracy: 0.3333 - val_loss: 0.8245
Epoch 54/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8889 - loss: 0.4827 - val_accuracy: 0.3333 - val_loss: 0.8274
Epoch 55/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.4807 - val_accuracy: 0.3333 - val_loss: 0.8310
Epoch 56/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.4786 - val_accuracy: 0.3333 - val_loss: 0.8340
Epoch 57/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.4763 - val_accuracy: 0.3333 - val_loss: 0.8370
Epoch 58/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8889 - loss: 0.4750 - val_accuracy: 0.3333 - val_loss: 0.8402
Epoch 59/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8889 - loss: 0.4726 - val_accuracy: 0.3333 - val_loss: 0.8427
Epoch 60/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.4707 - val_accuracy: 0.3333 - val_loss: 0.8450
Epoch 61/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - loss: 0.4703 - val_accuracy: 0.3333 - val_loss: 0.8465
Epoch 62/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - loss: 0.4683 - val_accuracy: 0.3333 - val_loss: 0.8493
Epoch 63/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4660 - val_accuracy: 0.3333 - val_loss: 0.8521
Epoch 64/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8889 - loss: 0.4642 - val_accuracy: 0.3333 - val_loss: 0.8551
Epoch 65/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4625 - val_accuracy: 0.3333 - val_loss: 0.8569
Epoch 66/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.4603 - val_accuracy: 0.3333 - val_loss: 0.8587
Epoch 67/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4596 - val_accuracy: 0.3333 - val_loss: 0.8604
Epoch 68/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4571 - val_accuracy: 0.3333 - val_loss: 0.8631
Epoch 69/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4557 - val_accuracy: 0.3333 - val_loss: 0.8657
Epoch 70/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - loss: 0.4558 - val_accuracy: 0.3333 - val_loss: 0.8695
Epoch 71/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.4520 - val_accuracy: 0.3333 - val_loss: 0.8717
Epoch 72/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4509 - val_accuracy: 0.3333 - val_loss: 0.8745
Epoch 73/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4508 - val_accuracy: 0.3333 - val_loss: 0.8752
Epoch 74/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4469 - val_accuracy: 0.3333 - val_loss: 0.8774
Epoch 75/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4455 - val_accuracy: 0.3333 - val_loss: 0.8793
Epoch 76/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4437 - val_accuracy: 0.3333 - val_loss: 0.8819
Epoch 77/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - loss: 0.4433 - val_accuracy: 0.3333 - val_loss: 0.8850
Epoch 78/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4405 - val_accuracy: 0.3333 - val_loss: 0.8872
Epoch 79/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4392 - val_accuracy: 0.3333 - val_loss: 0.8889
Epoch 80/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.4374 - val_accuracy: 0.3333 - val_loss: 0.8915
Epoch 81/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4364 - val_accuracy: 0.3333 - val_loss: 0.8930
Epoch 82/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4355 - val_accuracy: 0.3333 - val_loss: 0.8964
Epoch 83/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4329 - val_accuracy: 0.3333 - val_loss: 0.8990
Epoch 84/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - loss: 0.4314 - val_accuracy: 0.3333 - val_loss: 0.9017
Epoch 85/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4305 - val_accuracy: 0.3333 - val_loss: 0.9043
Epoch 86/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4285 - val_accuracy: 0.3333 - val_loss: 0.9052
Epoch 87/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.4279 - val_accuracy: 0.3333 - val_loss: 0.9068
Epoch 88/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4253 - val_accuracy: 0.3333 - val_loss: 0.9090
Epoch 89/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4239 - val_accuracy: 0.3333 - val_loss: 0.9116
Epoch 90/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8889 - loss: 0.4225 - val_accuracy: 0.3333 - val_loss: 0.9143
Epoch 91/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4210 - val_accuracy: 0.3333 - val_loss: 0.9171
Epoch 92/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8889 - loss: 0.4200 - val_accuracy: 0.3333 - val_loss: 0.9191
Epoch 93/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4181 - val_accuracy: 0.3333 - val_loss: 0.9212
Epoch 94/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.4169 - val_accuracy: 0.3333 - val_loss: 0.9239
Epoch 95/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4150 - val_accuracy: 0.3333 - val_loss: 0.9259
Epoch 96/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4143 - val_accuracy: 0.3333 - val_loss: 0.9283
Epoch 97/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4124 - val_accuracy: 0.3333 - val_loss: 0.9308
Epoch 98/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4108 - val_accuracy: 0.3333 - val_loss: 0.9336
Epoch 99/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8889 - loss: 0.4093 - val_accuracy: 0.3333 - val_loss: 0.9355
Epoch 100/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8889 - loss: 0.4081 - val_accuracy: 0.3333 - val_loss: 0.9377

In [50]:
history_mb = model.fit(X_train, y_train.values.reshape(-1,1), epochs=100, batch_size=20, verbose=1)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8889 - loss: 0.4067
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8889 - loss: 0.4065
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8889 - loss: 0.4064
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8889 - loss: 0.4062
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8889 - loss: 0.4061
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8889 - loss: 0.4059
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8889 - loss: 0.4058
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8889 - loss: 0.4056
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8889 - loss: 0.4054
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8889 - loss: 0.4053
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.8889 - loss: 0.4051
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.8889 - loss: 0.4050
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.8889 - loss: 0.4048
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.8889 - loss: 0.4047
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8889 - loss: 0.4045
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8889 - loss: 0.4044
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8889 - loss: 0.4042
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8889 - loss: 0.4041
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8889 - loss: 0.4039
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8889 - loss: 0.4037
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8889 - loss: 0.4036
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.8889 - loss: 0.4034
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8889 - loss: 0.4033
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.8889 - loss: 0.4031
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.8889 - loss: 0.4030
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.8889 - loss: 0.4028
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8889 - loss: 0.4027
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8889 - loss: 0.4025
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8889 - loss: 0.4023
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8889 - loss: 0.4022
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8889 - loss: 0.4020
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8889 - loss: 0.4019
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8889 - loss: 0.4017
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8889 - loss: 0.4016
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8889 - loss: 0.4014
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8889 - loss: 0.4012
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8889 - loss: 0.4011
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8889 - loss: 0.4009
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.8889 - loss: 0.4008
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.8889 - loss: 0.4006
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8889 - loss: 0.4005
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8889 - loss: 0.4003
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8889 - loss: 0.4001
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8889 - loss: 0.4000
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8889 - loss: 0.3998
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8889 - loss: 0.3997
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8889 - loss: 0.3995
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.8889 - loss: 0.3994
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8889 - loss: 0.3992
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8889 - loss: 0.3990
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8889 - loss: 0.3989
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.8889 - loss: 0.3987
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8889 - loss: 0.3986
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.8889 - loss: 0.3984
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.8889 - loss: 0.3983
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.8889 - loss: 0.3981
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8889 - loss: 0.3979
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8889 - loss: 0.3978
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.8889 - loss: 0.3976
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.8889 - loss: 0.3975
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.8889 - loss: 0.3973
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8889 - loss: 0.3971
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8889 - loss: 0.3970
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8889 - loss: 0.3968
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8889 - loss: 0.3967
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8889 - loss: 0.3965
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8889 - loss: 0.3964
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8889 - loss: 0.3962
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8889 - loss: 0.3960
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8889 - loss: 0.3959
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8889 - loss: 0.3957
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8889 - loss: 0.3956
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8889 - loss: 0.3954
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8889 - loss: 0.3952
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8889 - loss: 0.3951
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8889 - loss: 0.3949
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.8889 - loss: 0.3948
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.8889 - loss: 0.3946
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8889 - loss: 0.3945
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8889 - loss: 0.3943
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8889 - loss: 0.3941
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8889 - loss: 0.3940
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.8889 - loss: 0.3938
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8889 - loss: 0.3937
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8889 - loss: 0.3935
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8889 - loss: 0.3933
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8889 - loss: 0.3932
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8889 - loss: 0.3930
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8889 - loss: 0.3929
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8889 - loss: 0.3927
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8889 - loss: 0.3925
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8889 - loss: 0.3924
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8889 - loss: 0.3922
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8889 - loss: 0.3921
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8889 - loss: 0.3919
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8889 - loss: 0.3918
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8889 - loss: 0.3916
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.8889 - loss: 0.3914
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8889 - loss: 0.3913
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8889 - loss: 0.3911